version: 2
jobs:
  build:
    docker:
        - image: circleci/python:3.7
    working_directory: ~/app
    steps:
        - checkout

        - restore_cache:
            keys:
                - cache-{{ checksum "setup.py" }}

        - run:
            name: python module install
            command: |
                python3 -m venv venv
                . venv/bin/activate
                pip3 install --process-dependency-links -U -e .\[tests\]

        - save_cache:
            key: cache-{{ checksum "setup.py" }}
            paths:
                - ./venv

        - run:
            name: Lint
            command: |
                . venv/bin/activate
                find . -maxdepth 1 | grep '\.py$' | xargs flake8
                find . -maxdepth 1 | grep '\.py$' | xargs autopep8 -d | diff /dev/null -

        - run:
            name: Test Python codes
            command: |
                . venv/bin/activate
                python3 -m unittest discover .
